server:
  port: 8081

spring:
  main:
    web-application-type: reactive
  application:
    name: realtime-service
  data:
    mongodb:
      uri: mongodb://localhost:27017,localhost:27018/realtime_db?replicaSet=rs0
  devtools:
    restart:
      enabled: true
      exclude: static/**
    livereload:
      enabled: true
  jackson:
    default-property-inclusion: non_null
  webflux:
    server:
      idle-timeout: 60s

app:
  jwt:
    secret: zDhjJi+GFelRL2YYMwqQHWN43Rajge4zMLHtyrLznjfXkf+xr2r7FAgcI48e8UH7R7cgCx4y3ONyYwCMOhK2uA==
    expiration-ms: 86400000    # 24 hours (valid for int)
    refresh-expiration-ms: 2592000000  # 30 days (requires long)
    issuer: flexitech.realtime.provider.auth-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    persistAuthorization: true
  api-docs:
    path: /v3/api-docs

logging:
  file:
    name: D:/logs/flexitech-realtime-providers/realtime-service/realtime.log   # Path to log file
  level:
    root: INFO           # Default log level
    io.github.flexitech_realtime_provider: DEBUG  # Your package logging level
  logback:
    rollingpolicy:
      max-file-size: 10MB   # Rotate when file reaches 10MB
      max-history: 30       # Keep 30 days of logs

# external services
external-services:
  auth-service:
    url: http://localhost:8080